### ISSUE TITLE
Email does not include text() or attachment() when sending from Mac

### ISSUE THREAD

**Issue by andrewbcooper** [datawookie/emayili#29] opened 2020-01-31 17:58 UTC
Thank you for this amazing package!!!  I got it working perfectly on our server, but when I try to get it running on my Mac, I'm having some problems.  The e-mail sends without a hiccup (the from(), to(), and subject() parts of the envelope() all work.  But it's sending an empty e-mail - the text() doesn't show up (though it does when I use the same code on our server).  E.g.:

email <- envelope() %>%
  from("silly@silly.org") %>%
  to("notsilly@silly.org") %>%
  subject("This is a plain text message!") %>%
  text('Hello!') 

I've tried adding disposition and charset options, but they didn't seem to help.  Any thoughts on what might be going on?

Thanks again!!

**Comment by datawookie** [comment] 2020-02-04 14:59
Hi @andrewbcooper,

Firstly, nice set of initials: they match mine precisely. :)

Not quite sure what the issue here could be, but let's dig into it. Would you mind please sending me the same message from both server and Mac? That way I can take a look at the message contents and try to discern what the difference is.

Also, for reference, please add the precise code that you used to send the message to this issue.

You can find my email address in the package `DESCRIPTION` file.

Thanks,
Andrew.

**Comment by andrewbcooper** [comment] 2020-02-07 17:24
Thanks for all your help, Andrew!  We're getting little closer in figuring this out.  We think it's a security/firewall issue, but it's a strange one.  From my Mac and from 4 different servers, the following Python code works just fine: 

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import mimetypes

msg = MIMEMultipart()
msg['Subject'] = "Sending emails via Python"
msg['From'] = 'someone@somewhere'
msg['To'] = 'someone@somewhere'

msg.attach(MIMEText('Hello World!  Can you see me?', 'plain'))

s = smtplib.SMTP('SomeServer')
s.send_message(msg)
s.quit()

On 2 of the servers, emayili works just fine, but from my Mac and 2 other servers (all on the same network) the body of the message is stripped / empty.  They all ran the code:

email <- envelope() %>%
  from("someone@somewhere") %>%
  to("someone@somewhere") %>%
  subject("Sending emails via emayili") %>%
  text("Hello World!  Can you see me?") 

smtp <- server(host = "SomeServer", port = 25)
smtp(email,verbose = TRUE)

In examining the headers of the emails, the emails that contain the message body (via Python from anywhere or from 2 of the servers) all have: "X-Proofpoint-Virus-Version: vendor=fsecure engine=2.50.10434:6.0.138,18.0.572 definitions=2020-02-04_06:2020-02-04,2020-02-04 signatures=0" but those that do not contain the message body (from my Mac and 2 other servers) have just "X-Proofpoint-Virus-Version: ". The "vendor=fsecure....." is missing. Other than that, though, there were no differences in the email headers.

Still not sure why those differences exist for emayili on different servers (and why I don't get those same differences with Python), but we're getting closer.

**Comment by datawookie** [comment] 2020-02-19 09:29
Hi @andrewbcooper, sorry for the delay in getting back to you on this. I've been working on CRAN submission for `{emayili}` and a bunch of other things.

I'm assuming that this issue has not been resolved yet?

I was looking at the various test emails that you sent through.

Here is an extract from one of the emails which *did not* have any content:

![image](https://user-images.githubusercontent.com/6134409/74820395-97d02380-530a-11ea-9f2f-bcf2d2b0cfed.png)

I see what you mean about the `X-Proofpoint-Virus-Version` header entry being empty. I guess that this makes sense since if there is no content then presumably the virus checked won't run?

Here is an extract from one of the emails which *did* have any content:

![image](https://user-images.githubusercontent.com/6134409/74820246-5d668680-530a-11ea-9ad9-7cc936310e8c.png)

Now the `X-Proofpoint-Virus-Version` header entry does have content. Agreed, this is a major difference. But I also see something else: the message without a body had `Content-Type: text/plain` while the other one had `Content-Type: multipart/related`.

Now the thing is that messages sent from `{emayili}` should *always* have `Content-Type: multipart/related`. Always. So, TBH, I'm not convinced that the first message was actually generated with `{emayili}`.

So now I'm a little confused as to where these messages are being generated.

Could you perhaps generate another set of test messages by running precisely the same R script using `{emayili}` on both the server and your Mac. Add me to the list of recipients.

I'm sure that we can get to the bottom of this!

Thanks,
Andrew.

**Comment by datawookie** [comment] 2020-02-19 09:35
@andrewbcooper also, before you run the tests above, please grab the latest version of `{emayili}` from GitHub just so that we are looking at the same code too!

**Comment by datawookie** [comment] 2020-02-19 14:50
@andrewbcooper I've actually been working at a client today and tried to use `{emayili}` but ran into precisely the same issue. My working hypothesis right now is that the MS Exchange server is mangling the email content and replacing the correct MIME content with `text/plain`. There's actually a thread about this issue [here](https://social.technet.microsoft.com/Forums/exchange/en-US/f2c8efdf-6108-4d40-837b-f7af2386edde/exchange-2013-problem-with-multipartmixed-message?forum=exchangesvrsecuremessaging).

**Comment by datawookie** [comment] 2020-02-26 07:21
Hi @andrewbcooper, please install the latest version and test again. I think that the PR from @pmoulos cracked this issue. Thanks, Andrew.

**Comment by andrewbcooper** [comment] 2020-02-26 16:32
I sent you e-mails from 2 servers and my Mac.  It looks like my Mac now works, and the server that worked before still works.  But the second server does not seem to work.  Here's the script I ran on all three (just changing in subject line, and I removed the e-mail address and host name for privacy, for privacy)

devtools::install_github("datawookie/emayili",force=TRUE)
library(emayili)
library(dplyr)

email <- envelope() %>%
  from("") %>%
  to("") %>%
  subject("This is a plain text message from Ratchet Server Second Try.") %>%
  text("Hello World!  Can you see me?") 

smtp <- server(host = "",
               port = 25)

smtp(email,verbose = TRUE)

**Comment by datawookie** [comment] 2020-02-26 17:23
Hi Andrew,

Thanks for this.

Are you sure that you updated the package on the Ratchet server? The reason that I ask is that I not have a specific header record in emails sent with `{emayili}`. You can see that this is present in the emails from your Mac and the first server:

```
Subject: This is a plain text message from Second Dev Server.
X-Mailer: {emayili}-0.3.5
MIME-Version: 1.0
```

but absent from the other server:

```
Subject: This is a plain text message from Ratchet Server Second Try.
MIME-Version: 1.0
```

Besides this, I'm not sure that the problem is resolved for you because some parts of the rest of the message is being mangled too.

Anyway, please check that you have updated the package there too.

Sorry, I'm going to have to (again) delay working on this. I'm busy finalising a conference (http://joburg2020.satrdays.org/) for next weekend and it's an all-consuming business. I'll look at this again immediately after.

Thanks for your patience.

Best regards,
Andrew.

**Comment by datawookie** [comment] 2020-04-10 10:36
Hi @andrewbcooper,

I think that I might have resolved this issue. Would you be able to test?

Please install this commit from the `dev` branch.

```
remotes::install_github(
    "datawookie/emayili",
    ref = "a52143359cb2575309c8e71afd6457416d1a68bb"
)
```

Let me know what you find.

Thanks,
Andrew.

**Comment by datawookie** [comment] 2020-05-21 13:02
@andrewbcooper can you please test the above?

If I don't hear back from you then I'll assume that this is :+1: and I'll close the issue.

**Comment by datawookie** [comment] 2020-06-03 13:46
@andrewbcooper I never heard back from you, so I'm closing this issue. Feel free to reopen.

**Closed as completed by datawookie** 2020-06-03 13:46 UTC
