### ISSUE TITLE
Upgrading to 0.6.7 messes up html emails

### ISSUE THREAD

**Issue by andrewsrs** [datawookie/emayili#100] opened 2021-11-29 19:37 UTC
With  0.5.0 this:

```r
email <- envelope(to=to, from=from, subject=subject, html = "\<h2\>Hello\</h2\>\<p\>World\</p\>")
print(email, details=T)
```

produces

        Date:                     Mon, 29 Nov 2021 19:15:52 GMT
        X-Mailer:               {emayili}-0.5.0
        MIME-Version:      1.0
        To:                          xxxxxxx@xxx.xxx
        From:                     yyyyyyy@yyy.yyy
        Subject:                  test110
        Content-Type:                        text/html; charset=utf-8
        Content-Disposition:              inline
        Content-Transfer-Encoding:   quoted-printable
        
        <h2>Hello</h2><p>World</p>

And results in a properly formatted email.

With 0.6.7 the same call results in this:

      Date:                        Mon, 29 Nov 2021 19:15:52 GMT
      X-Mailer:                  {emayili}-0.6.7
      MIME-Version:         1.0
      To:                            xxxxxxxx@xxx.com
      From:                       yyyyyyyy@yyy.com
      Subject:                     test110
      Content-Type:                         text/html; charset=utf-8
      Content-Disposition:               inline
      Content-Transfer-Encoding:   quoted-printable
      Content-MD5:                         aK/lZkMt3u+Qpngbzn8i1Q==
      
      <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w=
      3.org/TR/REC-html40/loose.dtd">=3D0D=3D0A<html><body>=3D0D=3D0A<h2>Hello</h=
      2>=3D0D=3D0A<p>World</p>=3D0D=3D0A</body></html>=3D0D=3D0A

All the extra characters (`=3D0D-3D0A`) mess up previously perfectly formatted emails. What's going on?

**Comment by datawookie** [comment] 2021-12-01 06:46
Hi @andrewsrs,

Thanks for bringing this to my attention. I believe that this is now fixed in ce1b6ef726f001d7e03a034254e7850372fbe0f4 (v0.6.8). Please can you install from GitHub and test?

```r
remotes::install.github("datawookie/emayili", ref = "v0.6.8"
```

Thanks, Andrew.

**Closed as completed by datawookie** 2021-12-01 06:46 UTC

**Comment by wmcraver** [comment] 2021-12-21 00:20
I am not sure if @andrewsrs issue was resolved, but I just updated the emayili package today and am experiencing this issue.   We use this package to send a weekly digest email to our teams. The email contains long strings of text.  It looks like it breaks the line at 76 characters, inserting an equal sign. I've tried updating the package from GitHub.
![emayili message equal sign](https://user-images.githubusercontent.com/622307/146849897-50fe98ea-d3b8-4650-b8b9-42baa7ffa8f5.png)

The screenshot above is a snippet from the right side of the console for the message contents.

As an update, if I roll all the way back to v6.0.0, everything goes back to normal for me.

**Comment by datawookie** [comment] 2021-12-21 05:33
Hi @wmcraver,

Does this actually have any adverse effect on the received email? The reason for the 76 character line length, where longer lines are wrapped and terminated with a `=` is that HTML content is using [quoted-printable encoding](https://en.wikipedia.org/wiki/Quoted-printable).

For example:

```r
library(emayili)
library(dplyr)
library(stringi)

msg <- envelope(
  to = "alice@gmail.com",
  from = "bob@yahoo.com",
  subject= "Test HTML in {emayili} v0.7.1",
  html = paste0("<p>", stri_rand_lipsum(1), "</p>")
  )
```

If I print the raw content of the message then this is what I see:

```
Date:                        Tue, 21 Dec 2021 05:27:03 GMT
X-Mailer:                    {emayili}-0.7.1
MIME-Version:                1.0
To:                          alice@gmail.com
From:                        bob@yahoo.com
Subject:                     Test HTML in {emayili} v0.7.1
Content-Type:                text/html;
                              charset=utf-8
Content-Disposition:         inline
Content-Transfer-Encoding:   quoted-printable
Content-MD5:                 CmqEHEMDYkzTPxCcnGASjQ==

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w=
3.org/TR/REC-html40/loose.dtd">
<html><body><p>Lorem ipsum dolor sit amet, ornare tristique velit posuere, =
dictumst iaculis quisque sed felis, eu vel aliquam ut. Tempus etiam tempor =
posuere ut class augue at. Ornare dapibus massa eu a scelerisque, ut. Vesti=
bulum at ut suspendisse condimentum ligula id tincidunt sapien? Facilisis m=
agna mollis ut, purus turpis gravida purus neque. Nisl neque tellus volutpa=
t dui luctus. Non nunc mauris, mauris praesent, risus ridiculus mollis temp=
or. Pellentesque sed tincidunt. Augue a nunc penatibus sollicitudin eget ha=
c. Sit porttitor, morbi. Ac ad, interdum, varius sapien maecenas. Malesuada=
 maximus nam, donec maximus maximus facilisis. Condimentum ante, volutpat m=
aecenas purus, ac fusce ut. Eu blandit eros, aenean suscipit nec laoreet et=
 sed.</p></body></html>
```

However, if I look at the delivered message then this is what I see:

![image](https://user-images.githubusercontent.com/6134409/146876588-80045e78-c50c-4a19-be1c-0f314b1f45d3.png)

Looks fine because the email client understands the encoding and does the right thing with the content.

You can verify [here](https://www.smtpbucket.com/emails/ff8081817dd3e63e017ddb756240186a).

Please let me know if you have an example of the received email not looking okay and I'd be happy to debug.

Thanks, Andrew.

**Comment by wmcraver** [comment] 2021-12-21 14:00
For me, whenever there was an "=" inserted into the contents, it came through in the email messages.  It also appeared to replace the 77th character. Sometimes it replaces a part of an html line break or converts a gt or lt sign to gt or equal to, other times it's just consumes a space.

<img width="970" alt="Screen Shot 2021-12-21 at 6 53 59 AM" src="https://user-images.githubusercontent.com/622307/146941718-4d171808-eb97-4728-bf83-38f2a324d073.png">

**Comment by datawookie** [comment] 2021-12-21 18:56
Hi Mitch (@wmcraver), I'm happy to help, but you're going to have to provide me with a reproducible example. Unfortunately, a screenshot doesn't help me to debug any problems. I'd also need to know what OS and version of R you are running. Thanks, Andrew.

**Comment by wmcraver** [comment] 2021-12-22 15:18
Sorry for the delay.  

R Version: R 4.1.2 GUI 1.77 Big Sur ARM build (8007)
RStudio Version: 2021.09.1 Build 372
Emayili Version: 0.7.0 (from CRAN)
OS: Mac OS 12.0.1 (MacBook Pro 16" M1) also problematic on my work machine (Mac mini M1 same OS)

message body:
`"<b>Here are the latest updates for our XXXXXX team:</b><p><font style='font-family: Helvetica Neue, Helvetica, Arial, sans-serif;'><b>From Jocelyn:</b><br><ul><li>Libero enim sed faucibus turpis. Sed odio morbi quis commodo odio aenean. Quisque id diam vel quam elementum pulvinar etiam. Gravida neque convallis a cras semper auctor neque vitae. Porta nibh venenatis cras sed felis eget. Pharetra convallis posuere morbi leo urna molestie at elementum eu. Nibh sed pulvinar proin gravida. Imperdiet proin fermentum leo vel orci porta. Aenean euismod elementum nisi quis eleifend.</li></ul><p></font><font style='font-family: Helvetica Neue, Helvetica, Arial, sans-serif;'><b>From Mitch:</b><br><ul><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li></ul><p></font><font style='font-family: Helvetica Neue, Helvetica, Arial, sans-serif;'><b>From Jerrica:</b><br><ul><li>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li></ul><p></font>"`

Contents of the console after message is sent:
```
Found bundle for host smtp.office365.com: 0x6000026700c0 [serially]
Re-using existing connection! (#2) with host smtp.office365.com
Connected to smtp.office365.com (52.96.121.210) port 587 (#2)
MAIL FROM:<mitchell@xxxxxx.xxxxx>
250 2.1.0 Sender OK
RCPT TO:<mitchell@xxxxxx.xxxxx>
250 2.1.5 Recipient OK
DATA
354 Start mail input; end with <CRLF>.<CRLF>
Uploaded 2223 bytes...Date:                        Wed, 22 Dec 2021 15:05:55 GMT
X-Mailer:                    {emayili}-0.7.0
MIME-Version:                1.0
To:                          mitchell@xxxxxx.xxxxx
From:                        mitchell@xxxxxx.xxxxx
Subject:                     Weekly Update (12/22)
Content-Type:                text/html;
                              charset=utf-8
Content-Disposition:         inline
Content-Transfer-Encoding:   quoted-printable
Content-MD5:                 7XZ3nzjOgqbkxcpN4MK4cw==

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w=
3.org/TR/REC-html40/loose.dtd">
<html><body>
<b>Here are the latest updates for our XXXXXXX team:</b><p><font style=3D"font-=
family: Helvetica Neue, Helvetica, Arial, sans-serif;"><b>From Jocelyn:</b>=
<br><ul><li>Libero enim sed faucibus turpis. Sed odio morbi quis commodo od=
io aenean. Quisque id diam vel quam elementum pulvinar etiam. Gravida neque=
 convallis a cras semper auctor neque vitae. Porta nibh venenatis cras sed =
felis eget. Pharetra convallis posuere morbi leo urna molestie at elementum=
 eu. Nibh sed pulvinar proin gravida. Imperdiet proin fermentum leo vel orc=
i porta. Aenean euismod elementum nisi quis eleifend.</li></ul>
<p></p></font><font style=3D"font-family: Helvetica Neue, Helvetica, Arial,=
 sans-serif;"><b>From Mitch:</b><br><ul><li>Lorem ipsum dolor sit amet, con=
sectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dol=
ore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamc=
o laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in=
 reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariat=
ur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui offic=
ia deserunt mollit anim id est laborum.</li></ul>
<p></p></font><font style=3D"font-family: Helvetica Neue, Helvetica, Arial,=
 sans-serif;"><b>From Jerrica:</b><br><ul><li>Duis aute irure dolor in repr=
ehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. E=
xcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia de=
serunt mollit anim id est laborum.</li></ul>
<p></p></font></p>
</body></html>
Uploaded 2223 bytes... all done!
250 2.0.0 OK <SJ0PR16MB48597C________________________MB4859.namprd16.prod.outlook.com> [Hostname=SJ0PR16MB4859.namprd16.prod.outlook.com]
Connection #2 to host smtp.office365.com left intact
```

Screenshot of console:
<img width="1053" alt="emayili test message" src="https://user-images.githubusercontent.com/622307/147114756-559d4325-f15a-436c-8128-2856218b5ac5.png">

Screenshot of email: 
<img width="995" alt="Emayili outlook test message" src="https://user-images.githubusercontent.com/622307/147115667-eb203a54-80df-48c3-9cd8-72eec67bd084.png">


I tested with SMTP Bucket and everything comes through just fine. I upgraded to 0.7.1 from your repo before testing.  When I send the same message with my office365 credentials, the message still comes through funky. https://www.smtpbucket.com/emails/ff8081817dddd08d017de2cc240f383c

**Comment by datawookie** [comment] 2021-12-22 17:22
Hi Mitch (@wmcraver),

Thanks but

> I'm happy to help, but you're going to have to provide me with a reproducible example.

Please send me the code that you are using.

> I tested with SMTP Bucket and everything comes through just fine. I upgraded to 0.7.1 from your repo before testing. When I send the same message with my office365 credentials, the message still comes through funky.

Please can you clarify? So it's working fine with 0.7.1? How are you "send the same message with my office365 credentials"? Please help me to help you by providing a self-contained reproducible example of the code that is causing the problem.

Also, looking at the screenshot of the email :point_up: it seems fine to me. Can you please draw my attention to the problem?

Thanks, Andrew.

**Comment by wmcraver** [comment] 2021-12-22 17:47
>Please can you clarify? So it's working fine with 0.7.1? How are you "send the same message with my office365 credentials"?

Your package (v0.7.1) appears to work perfectly when using SMTP Bucket. It does not work for me (on two separate computers) when using the same envelope, but with Office365 as the SMTP host (instead of SMTP Bucket).

>Please help me to help you by providing a self-contained reproducible example of the code that is causing the problem.

I'm not sure what I can do to provide you with a self-contained reproducible example as it appears to be something Office365 is doing when it sends the email. I've provided all that I can aside from credentials to auth through O365.

>Also, looking at the screenshot of the email ☝️ it seems fine to me. Can you please draw my attention to the problem?

If you look at the screenshot of the email message received in Outlook, notice all of the "=" throughout the email.  These were not in the `msgBody` string before they were passed to the envelope and then sent. The first one can be seen on line 3 where it says `From Jocelyn:=br>`. The `<br>` tag gets broken and the `<` gets replaced with `=`.

It's entirely possible that Office365 is the problem, and I'm not sure what else I can provide you with to test this example. I get it, that you can't control what happens with different hosts and it's definitely not a reflection on the Emayili package.

**Comment by datawookie** [comment] 2021-12-22 18:03
Hi @wmcraver,

If you can't provide me with a (trimmed down and obfuscated if necessary) version of the code that you are running then I'm afraid I can't help you.

> I've provided all that I can aside from credentials to auth through O365.

Unless I've missed something, you have not provided me with the code that you are running! By all means strip out anything sensitive (like credentials and server addresses), but please send me the code.

Are you just using `{emayili}` to create the message but then you're actually sending it with `{Microsoft365R}`? If this is the case then I'm very much interested in resolving the problem because I imagine that this is not a niche application. We have already done some work to integrate these two packages but there might still be some issues that need to be hammered out.

Thanks, Andrew.

**Comment by datawookie** [comment] 2021-12-22 18:10
Hi @wmcraver, it would be helpful for me to see how the message is being mangled. Can you please send me an email using your setup? You can find my address in `DESCRIPTION`. Thanks, Andrew.

**Comment by wmcraver** [comment] 2021-12-22 18:10
>If you can't provide me with a (trimmed down and obfuscated if necessary) version of the code that you are running then I'm afraid I can't help you.
>I've provided all that I can aside from credentials to auth through O365.
>Unless I've missed something, you have not provided me with the code that you are running! By all means strip out anything sensitive (like credentials and server addresses), but please send me the code.

It's not like I'm doing something magical to build the msgBody.  Below is your requested code sample.

```
library(emayili)

msgBody = "<b>Here are the latest updates for our XXXXXX team:</b><p><font style='font-family: Helvetica
Neue, Helvetica, Arial, sans-serif;'><b>From Jocelyn:</b><br><ul><li>Libero enim sed faucibus turpis
. Sed odio morbi quis commodo odio aenean. Quisque id diam vel quam elementum pulvinar etiam. 
Gravida neque convallis a cras semper auctor neque vitae. Porta nibh venenatis cras sed felis eget. 
Pharetra convallis posuere morbi leo urna molestie at elementum eu. Nibh sed pulvinar proin gravida. 
Imperdiet proin fermentum leo vel orci porta. Aenean euismod elementum nisi quis eleifend.</li></ul><p>
</font><font style='font-family: Helvetica Neue, Helvetica, Arial, sans-serif;'><b>From Mitch:</b><br><ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore 
et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut 
aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum 
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia 
deserunt mollit anim id est laborum.</li></ul><p></font><font style='font-family: Helvetica Neue, Helvetica, 
Arial, sans-serif;'><b>From Jerrica:</b><br><ul><li>Duis aute irure dolor in reprehenderit in voluptate velit 
esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
culpa qui officia deserunt mollit anim id est laborum.</li></ul><p></font>"

msgTo = "mitchell@xxxx.com"
msgFrom = "mitchell@xxxx.com"
msgSubject = "This is a test subject."

smtp = server(
  host = "smtp.office365.com",
  port = "587",
  username = "mithell@xxxx.com",
  password = "myO365password",
  max_times = 2
)

msg = envelope(
  to = msgTo,
  from = msgFrom,
  subject = msgSubject,
  html = msgBody
)

smtp(msg, verbose = TRUE)
```

**Comment by datawookie** [comment] 2021-12-22 18:16
> It's not like I'm doing something magical to build the msgBody. Below is your requested code sample.

True. But now I don't need to _guess_ what you are doing.

Please send me an email message so that I can delve into the contents.

**Comment by datawookie** [comment] 2021-12-22 18:19
Just run your code, replacing your SMTP server with my GMail details and it went through 100% fine. So let me see how this looks when you send it.
